### ISSUE TITLE
使用create-react-app创建项目引入picker-react的问题

### ISSUE THREAD

**Issue by bihongbin3027** [ruoru/picker-react#3]
./node_modules/picker-react/src/components/GroupPicker.js
Module parse failed: Unexpected token (54:12)
You may need an appropriate loader to handle this file type.
|
|         return show && (
|             <PickerMask
|                 show={show}
|                 transparent={transparent}

**Comment by ruoru** [comment]
这个错误看来应该没有对应的loader支持这种语法格式的，我会追踪一下，谢谢。

**Comment by hyunchi** [comment]
这个bug还没解决吗，我下载下来也是这样

**Comment by ruoru** [comment]
不好意思 明天立马解决

**Comment by ruoru** [comment]
今天已经已经解决了，版本1.1.0 以上，非常抱歉哈哈，已经可以正常安装了。
